# Generated by Django 5.0.4 on 2024-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='test', max_length=158, verbose_name='username'),
            preserve_default=False,
        ),
    ]
