# Generated by Django 5.0.4 on 2024-08-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('dateOfBirth', models.DateTimeField()),
                ('lastLocationUpdate', models.DateTimeField(blank=True, null=True)),
                ('parentUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='account.parent')),
            ],
        ),
    ]
